FROM node:20-slim AS base

WORKDIR /student-portal/

COPY package.json package-lock.json /student-portal/

COPY frontend/student-portal/package.json /student-portal/frontend/student-portal/

RUN npm ci --workspace frontend/student-portal

COPY frontend/student-portal/ /student-portal/frontend/student-portal/

RUN npm run build --workspace frontend/student-portal

FROM node:20-slim

WORKDIR /app

RUN npm install -g serve

COPY --from=base /student-portal/frontend/student-portal/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]