---
  name: Building-on-push
  on:
    push:
      branches: 
      - 'feat/**'
  
  jobs:
    code-checkout:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v6
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}
            show-progress: true  #Show progress of the checkout action. Default true
            lfs: false
        - name: Install node
          uses: actions/setup-node@v6
          with:
            node-version: '20'
            cache: 'npm'