name: Building-on-push

on:
  push:
    branches:
      - "feat/**"
      - "dev/**"
jobs:
  format:
    runs-on: ubuntu-latest

    outputs:
      formatted: ${{ steps.prettier.outcome == 'failure' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Ensure required tools are installed
        id: check-tools
        continue-on-error: false
        run: |
          if npx --no-install prettier --version &> /dev/null; then
            echo "Prettier is already installed."
          else
            echo "Prettier is not installed. Installing..."
            npm install --no-save prettier
          fi

          if npx --no-install eslint --version &> /dev/null; then
            echo "ESLint is already installed."
          else
            echo "ESLint is not installed. Installing..."
            npm install --no-save eslint
          fi
      - name: Check formatting
        id: prettier
        continue-on-error: true
        run: npx prettier --check .

      - name: Fix formatting
        if: steps.prettier.outcome == 'failure'
        run: npx prettier --write .

      - name: Commit formatting changes
        if: steps.prettier.outcome == 'failure'
        env:
          GIT_USER: ${{ github.actor }}
          GIT_EMAIL: ${{ secrets.GIT_MAIL }}
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "style: apply prettier formatting {{ github.sha}}"

      - name: Push formatting changes
        if: steps.prettier.outcome == 'failure'
        run: |
          git push origin HEAD:${{ github.ref_name }}

  quality:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Security audit
        run: npm audit --omit=dev --audit-level=high

      - name: Lint code
        id: lint
        run: npm run lint

      - name: Commit lint fixes
        if: steps.lint.outcome == 'failure'
        env:
          GIT_USER: ${{ github.actor }}
          GIT_EMAIL: ${{ secrets.GIT_MAIL }}
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "fix: apply linting fixes"

  build:
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
