name: Building-on-commit
on:
  push:
    branches: 
    - feat/*

jobs:
  code-checkout:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v6
      - name: Checkout code
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          show-progress: true // Show progress of the checkout action. Default true
          token: ${{ secrets.GITHUB_TOKEN }} 
          lfs: false

      - name: Install node
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'