name: CI-feature

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"

jobs:
  Finding-the-differenece:
    runs-on: ubuntu-latest

    outputs:
      frontend_changed: ${{steps.changes.outputs.frontend}}
      backend_changed: ${{steps.changes.outputs.backend}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          fetch-depth: 0

      - name: Detect changed files
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            shared:
              - 'shared/**'
  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: |
          npx eslint . -f html -o eslint-report-${{ github.workflow }}.html
          npx eslint . -f json -o eslint-report.json

          ERROR_COUNT=$(jq '[.[].errorCount] | add' eslint-report.json)
          WARNING_COUNT=$(jq '[.[].warningCount] | add' eslint-report.json)

          echo "Errors: $ERROR_COUNT"
          echo "Warnings: $WARNING_COUNT"

          echo "errors=$ERROR_COUNT" >> $GITHUB_OUTPUT
          echo "warnings=$WARNING_COUNT" >> $GITHUB_OUTPUT

          if [ "$ERROR_COUNT" -gt 0 ] || [ "$WARNING_COUNT" -gt 0 ]; then
            exit 1
          fi

      - name: Upload ESLint report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: eslint-report-${{ github.run_id }}
          path: |
            eslint-report-${{ github.workflow }}.html
          if-no-files-found: ignore

  Formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm

      # - name: Install dependencies
      #  run: npm ci

      - name: Check formatting
        run: npx prettier . --check

  Secret-Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true

  Unit-Tests:
    runs-on: ubuntu-latest
    needs:
      - Finding-the-differenece
      - Linting
      - Formatting
      - Secret-Scanning
    steps:
      - name: Checkout code college-erp
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.MERN_ERP_TOKEN }}
          path: erp

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: "erp/package-lock.json"

      - name: Install ERP dependencies
        working-directory: erp
        run: npm ci

      - name: Checkout code college-erp-test
        uses: actions/checkout@v5
        with:
          repository: junaid-13/college-erp-microservices-testing
          token: ${{ secrets.TEST_TOKEN }}
          path: erp-test

      - name: Install dependencies college-erp-test
        working-directory: erp-test
        run: |
          npm install

      #- name: Debug workspace
      #  working-directory: erp-test
      #  run: |
      #    pwd
      #    ls -la
      #    find . -maxdepth 2 -type f | head -50

      - name: Run Frontend Unit Tests
        if: needs.Finding-the-differenece.outputs.frontend_changed == 'true'
        working-directory: erp-test
        run: |
          echo "Frontend changes detected"
          npx vitest --run

      - name: Run Backend Unit Tests
        if: needs.Finding-the-differenece.outputs.backend_changed == 'true'
        run: |
          echo "Backend changes detected"
